name = "cf-ai-resnik-voice-assistant"
main = "src/worker.js"
compatibility_date = "2024-10-31"
node_compat = true

# Workers AI binding for Llama 3.3
[ai]
binding = "AI"

# Durable Objects for conversation state management
[[durable_objects.bindings]]
name = "CONVERSATION_STATE"
class_name = "ConversationState"
script_name = "cf-ai-resnik-voice-assistant"

[[migrations]]
tag = "v1"
new_classes = ["ConversationState"]

# Environment variables
[env.production]
name = "cf-ai-resnik-voice-assistant"

[env.development]
name = "cf-ai-resnik-voice-assistant-dev"

# Build configuration
[build]
command = ""

# Limits and performance
[limits]
cpu_ms = 50000  # 50 seconds for AI processing

# Rate limiting
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "resnik_api_limiter"
# 100 requests per minute per user
simple = { limit = 100, period = 60 }
